In [2]:
!pip3 install pandas numpy

In [3]:
!which python3

/usr/bin/python3


In [5]:
import numpy as np

In [6]:
l = [i for i in range(10)]

In [7]:
ar = np.array(l)

In [15]:
ar.mean()
ar.min()
ar.max()

9

In [20]:
ar.dtype

dtype('int64')

In [23]:
ex = list([1, 2, 3, 's'])

In [24]:
np.array(ex)

array(['1', '2', '3', 's'], dtype='<U21')

In [33]:
m = np.array([[1,2],[3,4]]); m

array([[1, 2],
       [3, 4]])

In [35]:
m[0][1] = 9

In [36]:
m

array([[1, 9],
       [3, 4]])

In [37]:
m.shape

(2, 2)

In [39]:
m2 = np.array([[1, 2, 3, 4, 5]]); m2

array([[1, 2, 3, 4, 5]])

In [40]:
m2.shape

(1, 5)

In [42]:
m2.shape = (5, 1); m2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [46]:
m2.reshape(1, 5); m2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [53]:
b = np.linspace(0, 4, 4); b**2

array([ 0.        ,  1.77777778,  7.11111111, 16.        ])

In [54]:
c = np.arange(24).reshape(2,3,4); c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [55]:
c.ndim

3

In [70]:
ar = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [71]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
#Lignes 2 et 3 et colonnes 1 et 2
ar[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [75]:
# juste la 2eme ligne
ar[1,:]

array([4, 5, 6])

In [76]:
ar[:,-1]

array([3, 6, 9])

In [77]:
ar==2

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [78]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A,B

(array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]]))

In [81]:
A+B

array([[3, 1],
       [3, 5]])

In [87]:
a = np.array([7, 7, 2, 7, 3]); a

array([7, 7, 2, 7, 3])

In [88]:
a.argmax()

0

In [84]:
a.argmin()

0

In [90]:
b = np.array([[1, 2], [3, 4]]); b

array([[1, 2],
       [3, 4]])

In [92]:
sum(b)

array([4, 6])

In [94]:
b.sum(axis=1)

array([3, 7])

In [95]:
b.sum(axis=0)

array([4, 6])

In [96]:
np.array([1, 2, 3, 4]).cumsum()

array([ 1,  3,  6, 10])

In [103]:
np.arange(0, 10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [104]:
np.tile(3,8)

array([3, 3, 3, 3, 3, 3, 3, 3])

In [1]:
z = np.zeros((2,4)); z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [110]:
type(z)

numpy.ndarray

In [2]:
6*z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((2,4), dtype='int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [ ]:
np.diag(np.array())