# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [3]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [11]:
print(np.__version__)
print("\n")
np.show_config()

1.19.2


blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### Q3 : Créer un vecteur nul de taille 10

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [15]:
ar = np.zeros(10)
ar[4] = 1
ar

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [21]:
Z = np.arange(10,51); Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [22]:
Z[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [23]:
m = np.array([[0, 1, 2], [3, 4, 5], [6, 7 ,8]]); m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [25]:
md = np.diag(np.array([1, 1, 1])); md

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [26]:
mr = np.random.rand(3, 3); mr

array([[0.29788753, 0.22991203, 0.622666  ],
       [0.71035919, 0.49993405, 0.82255408],
       [0.07146437, 0.01758601, 0.86282545]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [29]:
mr2 = np.random.rand(10, 10);
mr2.max()

0.9968146521090533

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [37]:
mr3 = np.array([1, 2, 3, 4]); mr3
np.diag(mr3, -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [39]:
list = np.sum(np.random.rand(5)); list

3.032658384839979

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [40]:
list = np.mean(np.random.rand(5)); list

0.5338499457408138

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [46]:
l = [x for x in range(11)];

def sumTab ( tab ) :
    print(len(tab))
    
sumTab(l)

11


#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [57]:
tab = np.random.rand(10); tab

array([0.08719806, 0.6874339 , 0.74830358, 0.91630478, 0.57445148,
       0.01268193, 0.46337963, 0.32100097, 0.44527162, 0.25358041])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [68]:
A = [1, 2, 3, 4, 5]
B = [1, 2, 3, 4, 5]

A.sort()
B.sort()

if A == B :
    print("True")
else :
    print("False")

True


#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [93]:
Tab17 = np.ones((1,10), dtype='float32')
print(Tab17)
print(Tab17.dtype)

Tab17 = Tab17.astype('int32')
print(Tab17)
print(Tab17.dtype)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
float32
[[1 1 1 1 1 1 1 1 1 1]]
int32


#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)